### ISSUE TITLE
Regression in 3.2.2, 

### ISSUE THREAD

**Issue by weliem** [hypfvieh/dbus-java#114]
My library (https://github.com/weliem/blessed-bluez) uses your library and I just tried updating from 3.2.1 to 3.2.2.

After updating, I noticed this regression. When starting a Bluetooth discovery, I handle the signals that are sent by the adapter. However, in 3.2.2 no signals arrive and I see these warnings in the log:

[DBus Worker Thread-1] WARN org.freedesktop.dbus.messages.DBusSignal - Could not find suitable constructor for class org.freedesktop.dbus.interfaces.Properties$PropertiesChanged with argument-types: [class java.lang.String, class org.freedesktop.dbus.DBusMap, class java.util.ArrayList]
[DBus Worker Thread-2] WARN org.freedesktop.dbus.messages.DBusSignal - Could not find suitable constructor for class org.freedesktop.dbus.interfaces.Properties$PropertiesChanged with argument-types: [class java.lang.String, class org.freedesktop.dbus.DBusMap, class java.util.ArrayList]
[DBus Worker Thread-3] WARN org.freedesktop.dbus.messages.DBusSignal - Could not find suitable constructor for class org.freedesktop.dbus.interfaces.Properties$PropertiesChanged with argument-types: [class java.lang.String, class org.freedesktop.dbus.DBusMap, class java.util.ArrayList]
[DBus Worker Thread-4] WARN org.freedesktop.dbus.messages.DBusSignal - Could not find suitable constructor for class org.freedesktop.dbus.interfaces.Properties$PropertiesChanged with argument-types: [class java.lang.String, class org.freedesktop.dbus.DBusMap, class java.util.ArrayList]

Looks like a contructor was removed in 3.2.2. When I switch back to 3.2.1, everything works fine again.

Any thoughts?

**Comment by hypfvieh** [comment]
This is a regression introduced by changing signal processing to support multiple signals with the same name but different arguments (#110).

I pushed a fix for it, please test again with the snapshot. I will create a new release if this is working for you.

Another side note:
I don't think it is a good idea to copy classes from bluez-dbus to your project.

Any updates and changes/fixes added upstream will then be missing in your copy.
Also you will then mess up with the package name, which may cause trouble if someone uses bluez-dbus and your library in the same project. This may also fail if java's new modularization feature may be used in bluez-dbus in the future.

I would appreciate if you would contribute your changes to bluez-dbus as pull requests and use bluez-dbus as dependency in your project. This way anyone can profit from fixes/additions in bluez-dbus.

**Comment by weliem** [comment]
Hi, thanks for the fix! I tried the snapshot and it is working now! Would be great if you can do a release...

As for bluez-dbus, I will contribute back with PRs once I get into stable waters. I just started my library and it is still very early. I am making tons of changes all the time. For now it was easier to copy the files and make changes as I go...

But I am very thankful for your work! Good job!
