### ISSUE TITLE
Use compiled patterns in the org.freedesktop.dbus.connections.AbstractConnection

### ISSUE THREAD

**Issue by OlegAndreych** [hypfvieh/dbus-java#119]
My proposal is to compile patterns from the `org.freedesktop.dbus.connections.AbstractConnection`.

I've found that compiling of the `org.freedesktop.dbus.connections.AbstractConnection#OBJECT_REGEX_PATTERN` in the constructor of the `org.freedesktop.dbus.messages.DBusSignal#DBusSignal(java.lang.String, java.lang.Object...)` is rather hot.

**Comment by hypfvieh** [comment]
changes merged, thank you
