### ISSUE TITLE
Possibility to disable share dbus connection cache during connection creation

### ISSUE THREAD

**Issue by lbeuster** [hypfvieh/dbus-java#14]
Currently there are only static methods to get a dbus connection. These methods use a static map that return always the same connection instance for the same address. Especially in tests where you simulate server and client this is not a good idea.
I would be nice to create independant dbus connections.

* One simple solution could be to make the constructor DBusConnection.<init>(address, registerSelf) public. And extract the auto detection code to a static method. Client code would look like
```
connection = new DBusConnection(DBusConnection.autoDetectAddress(SESSION), false);
```
* Another could be to add more factory methods. Perhaps getConnection-methods that use the static map and newConnection methods that always create a new connection

What do you think? If we have a decision I could create a pull request.

**Comment by hypfvieh** [comment]
I can remember exactly why, but allowing the outside world to create multiple DBusConnections in the same application does not work that well.

I came accross that problem while refactoring dbus-java for version 3.0.
After cleaning up, I wanted to get rid of the static stuff and shared connections.
But after removing this part and using the constructor directly, the connection did not work at all.

If I remember correctly it was an issue with the Unix-Socket stuff.
If you try to connect to DBus using UnixSocket multiple times from the same application your connection will be refused. 

So even if it would be possible to create multiple DBusConnections it would cause trouble later on, or does not behave like expected.

**Comment by hypfvieh** [comment]
Sorry, I don't know which setup it was, it's just too long ago...

I'm also sure that this is not a DBus problem. 
I guess it's more an issue of the UnixSocket library (libmatthew) and/or the integrated SASL stuff.

**Comment by lbeuster** [comment]
I will try a little bit to reproduce it...

**Comment by lbeuster** [comment]
I created a stress test with several services and several clients in the same JVM each using it's own DBusConnection. I could not produce any error on Mac and Ubuntu. That's the expected behavior. Maybe there was a mistake during your refactoring or perhaps something in my test is wrong. 
If you want to have a look on it... 

https://github.com/lbeuster/dbus-java/tree/no_shared_connection

And please feel free to add it to dbus-java.

**Comment by hypfvieh** [comment]
I added your test and changes to 32442c1.
Thanks for your contribution. I'll close this ticket now.
