### ISSUE TITLE
Is there a way to disable logging?

### ISSUE THREAD

**Issue by weliem** [hypfvieh/dbus-java#144]
Hi,

I am using slf4j throughout my application and when I put the log level to DEBUG, there is a massive amount of log items coming from this library. 

It would be handy if I could switch of logging for this library only so I can only see my app's log items.

Is it possible?

**Comment by hypfvieh** [comment]
This can be done by configuring your logging backend.
If you use logback, you can add this to your logback.xml:
```
<logger name="org.freedesktop.dbus"                             level="INFO" />
```
If you use log4j2, you have to add this to the <Loggers> Section:
```
<Logger name="org.freedesktop.dbus"                             level="INFO" />
```
In both cases, logging of dbus-java would only be visible if it is logged on level INFO or higher.

**Comment by weliem** [comment]
I don't want to put the log to INFO because then I don't see the other DEBUG logging from my application anymore. There are many other components in my application that do logging.

So what I meant was that I want to turn off logging only for the library while the rest of my application can still log on DEBUG level.

**Comment by hypfvieh** [comment]
This is what I told you. 
The settings given above will set the log level to INFO for all Loggers starting with 'org.freedesktop.dbus' - so every logger used in dbus-java will only log INFO or above. It will not change anything related to YOUR loggers as long as your loggers are not in org.freedesktop.dbus package or start with that name.

**Comment by weliem** [comment]
Works! I just misunderstood your first answer...

Thank you . Closing issue
