### ISSUE TITLE
Failure in compiling tests

### ISSUE THREAD

**Issue by poeschel** [hypfvieh/dbus-java#151]
[Current](https://github.com/hypfvieh/dbus-java/commit/036ab5d6e5a84be8dce25454ecc04ae32af2916d) Version in master branch fails compiling the tests.
More specifically:
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project dbus-java: Compilation failure: Compilation failure:

[ERROR] /home/larsi/projekte/dbus-java/dbus-java/src/test/java/org/freedesktop/dbus/test/MarshallingTest.java:[32,38] cannot find symbol
[ERROR]   symbol: class AbstractBaseTest
[ERROR] /home/larsi/projekte/dbus-java/dbus-java/src/test/java/org/freedesktop/dbus/test/MarshallingTest.java:[78,117] cannot find symbol
[ERROR]   symbol:   method getClass()
[ERROR]   location: class org.freedesktop.dbus.test.MarshallingTest
[ERROR] /home/larsi/projekte/dbus-java/dbus-java/src/test/java/org/freedesktop/dbus/test/MarshallingTest.java:[78,211] cannot find symbol
[ERROR]   symbol:   method getClass()
[ERROR]   location: class org.freedesktop.dbus.test.MarshallingTest
[ERROR] /home/larsi/projekte/dbus-java/dbus-java/src/test/java/org/freedesktop/dbus/test/MarshallingTest.java:[78,308] cannot find symbol
[ERROR]   symbol:   method getClass()
[ERROR]   location: class org.freedesktop.dbus.test.MarshallingTest
[ERROR] /home/larsi/projekte/dbus-java/dbus-java/src/test/java/org/freedesktop/dbus/test/MarshallingTest.java:[84,9] cannot find symbol
[ERROR]   symbol:   method assertTrue(boolean,java.lang.String)
[ERROR]   location: class org.freedesktop.dbus.test.MarshallingTest
[ERROR] /home/larsi/projekte/dbus-java/dbus-java/src/test/java/org/freedesktop/dbus/test/MarshallingTest.java:[86,9] cannot find symbol
[ERROR]   symbol:   method assertTrue(boolean,java.lang.String)
[ERROR]   location: class org.freedesktop.dbus.test.MarshallingTest
[ERROR] /home/larsi/projekte/dbus-java/dbus-java/src/test/java/org/freedesktop/dbus/test/MarshallingTest.java:[100,9] cannot find symbol
[ERROR]   symbol:   method assertTrue(boolean,java.lang.String)
[ERROR]   location: class org.freedesktop.dbus.test.MarshallingTest
[ERROR] /home/larsi/projekte/dbus-java/dbus-java/src/test/java/org/freedesktop/dbus/test/MarshallingTest.java:[102,9] cannot find symbol
[ERROR]   symbol:   method assertEquals(java.lang.String,java.lang.String,java.lang.String)
[ERROR]   location: class org.freedesktop.dbus.test.MarshallingTest
[ERROR] /home/larsi/projekte/dbus-java/dbus-java/src/test/java/org/freedesktop/dbus/test/MarshallingTest.java:[103,9] cannot find symbol
[ERROR]   symbol:   method assertEquals(java.lang.String,java.lang.String,java.lang.String)
[ERROR]   location: class org.freedesktop.dbus.test.MarshallingTest
[ERROR] -> [Help 1]`
Even when skipping execution of tests, it tries to compile them.

Since commit 2e171f152a3e71810ed06a4f8c58d9b3fad2ad25 `MarshallingTest` inherits from `AbstractBaseTest`, which I do not see in the repo.

**Comment by hypfvieh** [comment]
This is caused by a backport of some tests from the java16 branch. I just pushed the required changes to fix this.

**Comment by poeschel** [comment]
Thank you!
Works as expected!
