### ISSUE TITLE
Java 8 requirement broken

### ISSUE THREAD

**Issue by Xerxekyran** [hypfvieh/dbus-java#152]
With commit 4875bdb6c2bf6c16962bc15d638e8c0299984692 a **List.of** was added to the code base (in org.freedesktop.dbus.messages.ExportedObject::getDBusInterfaces) which is as far as I know only supported starting with Java 9.
I would appreciate the next dbus-java version to stick to the minimum requirement of Java 8.

**Comment by hypfvieh** [comment]
Fixed in latest commit
