### ISSUE TITLE
Request to link to related application

### ISSUE THREAD

**Issue by brett-smith** [hypfvieh/dbus-java#154]
Not a bug!

I wondered if you would consider linking to my dbus-java related project, a d-feet clone [dj-feet](https://github.com/bithatch/dj-feet). It's primary audience would be users of dbus-java, so a link from your README.md would be ideal :)

It's pretty much identical to d-feet, save for differences imposed by lack of CSD type window you might see on GNOME. 

It written in JavaFX, and requires up to date versions of everything, including dbus-java-4.0.0-SNAPSHOT.  This is not a problem though, as there are installer builds for the 3 major operating systems, These do everything for you, including setting up a (very insecure) dbus-daemon service as a playground, as well as launchers for all the dbus-java tools. 

Thanks,

Brett

**Comment by hypfvieh** [comment]
I added this to the Wiki and added a small note in the readme where to find a list of applications using dbus-java

**Comment by brett-smith** [comment]
Perfect, thanks!
