### ISSUE TITLE
Refactor DBusDaemon to start embedded

### ISSUE THREAD

**Issue by lbeuster** [hypfvieh/dbus-java#16]
I'd like to do minimal possible refactoring to start the DBusDaemon embedded (e.g. for tests). Currently its only possible to do that with some reflection hacking.
What do you think?

**Comment by lbeuster** [comment]
No, I didn't. First have to figure out how to update my fork. Will do that now ;)

**Comment by hypfvieh** [comment]
Thanks for your PR, changes have been merged.
