### ISSUE TITLE
Request for API improvement with adding and removing signal handlers.

### ISSUE THREAD

**Issue by brett-smith** [hypfvieh/dbus-java#175]
This is not a bug, just a request for comments on possible API improvements to adding and removing signal handlers. 

For example, say I have a GUI app. In this app, one of the windows I open will add a set of signal handlers when the window opens, and remove them when the windows. The app has various different types of windows that might listen, or stop listening to, various signals.

The code to achieve this a bit clunky, especially when used with lambda syntax, and may require keeping references to multiple objects to be able to remove signals. 

```java
private DBusSigHandler<SomeDbusObject.MySignal> mySigHandler;
private SomeDbusObject myObject;

void setupSignals() {
    myObject = connection.getRemoteObject(BUS_NAME, ROOT_OBJECT_PATH, SomeDbusObject.class).
    mySigHandler = (e) -> {
        // Do stuff
    };
    connection.addSigHandler(SomeDbusObject.MySignal.class, myObject, mySigHandler);
}

void tearDownSignals() {
    connection.removeSigHandler(SomeDbusObject.MySignal.class, myObject, mySigHandler);
}
```

This is not terrible, but it can get a bit excessive when you have many signals. 

At the very least, it may be useful to do 2 things to reduce the typing a bit.

- Return the handler reference in `addSigHandler()`
- Provide a new `removeSigHandler()` than only takes the handler instance. 

So the above code becomes.

```java
private DBusSigHandler<SomeDbusObject.MySignal> mySigHandler;

void setupSignals() {
   mySigHandler =  connection.addSigHandler(SomeDbusObject.MySignal.class, 
     connection.getRemoteObject(BUS_NAME, ROOT_OBJECT_PATH, SomeDbusObject.class,  (e) -> {
        // Do stuff
    });
}

void tearDownSignals() {
    connection.removeSigHandler(mySigHandler);
}
```

**Comment by DaveJarvis** [comment]
>  Return the handler reference in addSigHandler()
>
>  Provide a new removeSigHandler() than only takes the handler instance.

While that works, a more object-oriented approach would be to use tokens and a Closeable implementation. Such as:

``` java
final var token = connection.addSigHandler( ... );
token.close();
```

It's a bit more flexible because the code that performs the closing doesn't need a handle to the `connection`, only the token.

**Comment by brett-smith** [comment]
Having a `Closeable` of some sort sounds good to me too. I'll get a PR together.

**Comment by hypfvieh** [comment]
The change has been merged, can we close this issue?

**Comment by DaveJarvis** [comment]
Does any library usage documentation/example need to be updated as part of the PR?

**Comment by hypfvieh** [comment]
I don't think so. But if you want to add some more samples or documentation, that would be great
