### ISSUE TITLE
Push to public Maven repository

### ISSUE THREAD

**Issue by DaveJarvis** [hypfvieh/dbus-java#187]
Any chance of getting a push to a central maven repository for 4.2.1?

Not found: https://mvnrepository.com/artifact/com.github.hypfvieh/dbus-java/4.2.1

Found: https://mvnrepository.com/artifact/com.github.hypfvieh/dbus-java/3.3.2

Greatly appreciate all the work that's gone into getting 4.2.1 out the door.

**Comment by hypfvieh** [comment]
The version is already in maven central - you are looking at the wrong artifact. 
Publishing is automated when I build the project using maven's release plugin.

[dbus-java](https://search.maven.org/artifact/com.github.hypfvieh/dbus-java/3.3.1/jar) is only for [version 3.x](https://mvnrepository.com/artifact/com.github.hypfvieh/dbus-java/3.3.2)
[dbus-java-core](https://search.maven.org/artifact/com.github.hypfvieh/dbus-java-core/4.2.1/jar) is [version 4.x](https://mvnrepository.com/artifact/com.github.hypfvieh/dbus-java-core/4.2.1)

See also the link found on top of README.md (seen on the landing page of the this repo)
