### ISSUE TITLE
OSGi dependency on unix sockets

### ISSUE THREAD

**Issue by DaveJarvis** [hypfvieh/dbus-java#188]
Is the OSGi dependency on unix sockets an absolute requirement?

https://github.com/hypfvieh/dbus-java/blob/b7dfd4710d91dd00f4e80cfa4174d229bba55866/dbus-java-osgi/pom.xml#L74

We don't/can't use unix sockets, so it seems a little strange to have OSGi listed as a dependency but not the TCP/IP sockets. I'd have thought we'd need either both or neither?

**Comment by hypfvieh** [comment]
I have to admit that I don't really care about the OSGi bundle. I don't use any OSGi stuff and I never really understood how this works.
If the dependency is wrong, feel free to provide a PR to remove it.

**Comment by DaveJarvis** [comment]
We removed the dependency. Thank you!
