### ISSUE TITLE
How can I actually use `withAutoConnect(false)`?

### ISSUE THREAD

**Issue by brett-smith** [hypfvieh/dbus-java#212]
I am trying to make use of `DirectConnection`, but have hit an issue with reliable synchronization of start up of the client and server parts of the code.

This problem is actually demonstrated by the `TestPeer2Peer` test, which I believe only actually works more through luck than actually being 100% solid. I intend to raise a separate issue for this, as it may take a little explanation. 

Anyway, to work around the problem, I need to use `withAutoConnect()`. This gives me a `DirectConnection` with an unconnected transport, but I see no way to then get at the `AbstractTransport` to call `listen()` myself (in a new thread). 

Is there something in the API I am missing?

**Comment by hypfvieh** [comment]
You are right, the method to connect a not-auto-connected transport is missing.
I updated the current code to include a `connect()` method which will connect the transport if it wasn't connected before.

**Comment by brett-smith** [comment]
Great, thanks for fast response.
