### ISSUE TITLE
SASL' MAX_READ_BYTES is too small

### ISSUE THREAD

**Issue by Prototik** [hypfvieh/dbus-java#215]
It's me from #214 again :upside_down_face: 

I encountered another issue with cookie auth this time.

Look at this: https://github.com/hypfvieh/dbus-java/blob/9bc3c2cbe95dcf45fd6fdcc6d59822650ebdab8c/dbus-java-core/src/main/java/org/freedesktop/dbus/connections/SASL.java#L43

So dbus-java would read at most 64 bytes for each line at auth stage, but let's do some math for cookie auth:
-5 bytes for `DATA ` prefix, leftover is hexencoded, so divide by 2 with rounding down = 29 bytes of actual data at max.
Cookie auth data consist of 3 parts: cookie context, cookie id and random part, space delimeted, so -2 bytes = 27.
Default cookie context is `org_freedesktop_java`, which is 20 bytes, leftover is 7 bytes.
Default cookie id is milliseconds since unix epoch, which is 12 bytes, leftover is... -5 bytes.
Default random part is 8 bytes long, so -13 bytes.

But that's only true for default settings of dbus-java, other implementation can use even longer parts, but as you can see even with that cookie auth is broken

**Comment by Prototik** [comment]
I believe another issue with cookie here:
The reason is https://github.com/hypfvieh/dbus-java/blob/9bc3c2cbe95dcf45fd6fdcc6d59822650ebdab8c/dbus-java-core/src/main/java/org/freedesktop/dbus/connections/SASL.java#L387-L390

Here is challenge string generated, but result of the operation is set to `OK`, which means `you authorized, go ahead and do what you want'. Instead it should be `CONTINUE` to send challenge string to the client... Can you confirm that?

Retrieving cookie from keyring is also buggy:
https://github.com/hypfvieh/dbus-java/blob/9bc3c2cbe95dcf45fd6fdcc6d59822650ebdab8c/dbus-java-core/src/main/java/org/freedesktop/dbus/connections/SASL.java#L99-L107
Both cookie filter clauses `(tm.getElapsedSeconds() + MAX_TIME_TRAVEL_SECONDS) < timestamp` and `tm.getElapsedSeconds() - EXPIRE_KEYS_TIMEOUT_SECONDS > timestamp)` contains `tm.getElapsedSeconds()`, which is seconds since *creating of TimeMeasure object*, so basically always is 0, and `timestamp` is *seconds since unix epoch*, which is always waaaay greater than zero, so comparing then is useless and not correct.

**Comment by Prototik** [comment]
@hypfvieh  Should I format these patches as pull request or it's fine for you to apply it manually?

**Comment by hypfvieh** [comment]
PRs are always welcome
