### ISSUE TITLE
2.7 Branch

### ISSUE THREAD

**Issue by Xerus2000** [hypfvieh/dbus-java#22]
As one important debugging issue wasn't fixed, would you consider creating a separate 2.7 branch that would be at the 2.7.5 tag? Then I would submit a PR there so you can upload the actually fixed version.

**Comment by hypfvieh** [comment]
I don't maintain 2.7 anymore.
The goal is to get 3.0 ready for release. Sadly more and more bugs are popping up delaying a new release.

Either you create a patch for 3.0 or  you just add the patch for your changes of 2.7 to this ticket and
I will implement the changes manually.

**Comment by Xerus2000** [comment]
I know you don't, but, like, for archive purposes. I got the patch ready, it's on my fork in the 2.7 branch.

**Comment by Xerus2000** [comment]
Are there any changes that may break the library in version 3? Otherwise I might as well switch ^^

**Comment by hypfvieh** [comment]
3.0 has a different package structure. It is no drop-in replacement.
It should be usable if you can fix the used imports in your project.
