### ISSUE TITLE
Structs in Properties, is it possible?

### ISSUE THREAD

**Issue by brett-smith** [hypfvieh/dbus-java#228]
I am interfacing with `org.freedesktop.resolve1.Manager`, the SystemD DNS interface.

Various properties use (arrays of) structs as their signature, but I can't seem to find a way to map these structs to Java objects like you can outside of `Properties`. 

![image](https://github.com/hypfvieh/dbus-java/assets/10938912/34c2c17a-94e8-489d-a106-ef6cd37fb13a)

Using `Properties.Get()` results in an `ArrayList` of `Object[]` containing each field of the struct. This is of course is usable, but involves lots of messy casting.

Is there a better way?

**Comment by brett-smith** [comment]
Ah great, `StructHelper` is an improvement, thanks.  I confess I wasn't really fully aware of the examples that exist now, I might have found StructHelper :)

On a more general note about `Properties`, I do wonder if they could be implemented in a more Java like way that would solve issues like this and make dealing with them easier.   

Perhaps it could be possible to deserialize Properties to an actual proxied Java type. Property names would be mapped to getters and setters, annotations could be used to add missing collection type data back in. Bonus points if it can be made to work with Java 's new`record`s for even less code (can you make a proxy record?). For convenience, `DBusInterface` implementations could somehow provide  direct access to these.

Unless you can think of a good reason not to, I might try and prototype something if i get some time!

Anyway, thanks again, closing as solved.

**Comment by hypfvieh** [comment]
Feel free to try to improve this.

I tried to a few times myself, always got stuck at some point missing essential information or having some sort of hen/egg issue. Having a solution which forces to create some weird struct classes is also not useful...
