### ISSUE TITLE
problem to execute DBusViewer

### ISSUE THREAD

**Issue by mtmmtm9** [hypfvieh/dbus-java#241]
When importing the code into intellij and clicking execute on DBusViewer i get:
..../src/main/java/module-info.java:6:40
java: module not found: org.freedesktop.dbus

**Comment by hypfvieh** [comment]
I don't see a problem here. Just downloaded latest Intellij, imported dbus-java project and started the viewer.
Same for Eclipse.

Did you open the complete project, or just the dbus-java-util submodule? 
The 'org.freedesktop.dbus' module is provided by dbus-java-core.

**Comment by mtmmtm9** [comment]
I imported the whole project and right-clicked on DBusViewer and selected Run. I did this using openjdk17 and latest intellij-community-edition on a raspberry pi. I will try with eclipse.

**Comment by mtmmtm9** [comment]
It works with eclipse. This must be a problem in intellij (on the pi) ?
