### ISSUE TITLE
Make dbus-java OSGi ready

### ISSUE THREAD

**Issue by svagionitis** [hypfvieh/dbus-java#32]
Hi David,

First of all thanks for this library, it is very helpful if you want to connect to DBus.

Now, checking the MANIFEST file of v3.0.0 jar file in the maven repository, I could see that there are not any metadata specific for an OSGi bundle, like `Import-Package`, `Export-Package`, etc. Are you considering to add them in a later release?

Regards,

Stavros

**Comment by hypfvieh** [comment]
Hi,

I'm not familiar with all this OSGi stuff (always looked very confusing to me), so no I have no plans to add this.

Anyways, if you want to provide the required manifest entries and stuff needed for OSGi compatibility, please feel free to send me a pull request.

**Comment by svagionitis** [comment]
Cool thanks David for the quick response. I am not so familiar with OSGi myself, but I will try to create a pull request with necessary changes.

**Comment by cdealti** [comment]
@svagionitis are you still working on this? If not I can do that.

**Comment by stack-head** [comment]
I've put out two PRs that might be suitable-you wouldn't want to merge both of them, either one or the other:
https://github.com/hypfvieh/dbus-java/pull/66
https://github.com/hypfvieh/dbus-java/pull/67

**Comment by hypfvieh** [comment]
Thanks for your PRs.
As I'm not familiar with that OSGi stuff, I'm not sure which PR would be "the better one".

If I understand correctly, using #66 would not be suitable as the required dependencies are not OSGi compliant. I don't think that we have the chance to convince every project to make there stuff OSGi compliant.

Using #67 will in deed create a very large bundle. 
I hate those fat-jars providing old versions of some libraries which were messing up other ones projects.

If my observations are correct, some kind of "hybrid" model would be great.

I would like to provide two different versions, one "fat" version which is OSGi ready (e.g. dbus-java-osgi), and the regular version we have right now (dbus-java).
Any idea on how to do this in one deployment step?

**Comment by stack-head** [comment]
As you state in your last statement, generating both a typical jar file and
a second "fat" bundle as separate outputs should be agreeable.  I spent a
bit of time reading, there seems to be a pretty strong consensus that
trying to produce two artifacts in a single pom.xml file is more trouble
than it's worth.  I think you could either:
1. maintain two separate pom files, one for each output,
2. Create a parent pom file with all the shared properties (pom packaging),
and two additional pom files that inherit from it-one would be jar
packaging, the other would be bundle packaging.  You may also choose to
differentiate between the two artifacts with either a different artifactId
or a different version (Think 3.2.0-SNAPSHOT and  3.2.0-bundled-SNAPSHOT),
I'm not sure what would be better.

Let me know if you'd favor one approach over the other, and I'll put out
another PR.  Thanks for the fast response.


------------------------------
*James O'Carroll* | james.ocarroll@stackhead.com

**Comment by hypfvieh** [comment]
What I was thinking about was some kind of additional module.

dbus-java already is a maven multi-module project, so I created a third module which builds an OSGi bundle.

Changes pushed, maybe you can have a look if this is working for you.

**Comment by stack-head** [comment]
This is great, this works just fine for me.  Thank you, feel free to close
the two PRs.  Have a good one.


------------------------------
*James O'Carroll* | james.ocarroll@stackhead.com

**Comment by hypfvieh** [comment]
I guess the OSGi stuff is now solved. I'll close this ticket.
