### ISSUE TITLE
Incorrect imports generated by CreateInterface

### ISSUE THREAD

**Issue by sshort** [hypfvieh/dbus-java#49]
CreateInterface generates code using some hard coded imports that refer to the old package names for some refactored classes, including:

In createException:
   out.println("import org.freedesktop.dbus.DBusExecutionException;");

In createTuple():
    out.println("import org.freedesktop.dbus.Position;");

These should be:
   out.println("import org.freedesktop.dbus.exceptions.DBusExecutionException;");
   out.println("import org.freedesktop.dbus.annotations.Position;");

**Comment by hypfvieh** [comment]
I merged your PR. 
Anyway CreateInterface is legacy code and should no longer be used as it will be removed in the future...

**Comment by sshort** [comment]
What's going to replace it?

**Comment by hypfvieh** [comment]
see: [Issue 35](https://github.com/hypfvieh/dbus-java/issues/35#issuecomment-449394979)

**Comment by sshort** [comment]
Ah - sorry - I completely missed that.  I'll give it a go.
