### ISSUE TITLE
jnr-unixsocket with MacOS support

### ISSUE THREAD

**Issue by lbeuster** [hypfvieh/dbus-java#55]
The current 3.2.0-SNAPSHOT doesn't work with MacOS because the UnixSocketOption SO_PASSCRED is not supported on MacOS.
A quick google search returned some Chromium code at: https://chromium.googlesource.com/chromium/src/base/+/master/posix/unix_domain_socket.cc. They just omitted the option if MacOS is running. All my local tests passed without setting this option.

I could provide a merge request...

**Comment by hypfvieh** [comment]
Yes please. Pull requests are always welcome.

**Comment by hypfvieh** [comment]
Fixed with PR #57
