### ISSUE TITLE
DBusConnection.close() should release requested bus names

### ISSUE THREAD

**Issue by lbeuster** [hypfvieh/dbus-java#62]
I think a non shared connection should release any requested busnames on close(). With 2.7.x it still worked. With 3.2.x not (don't know the state of 3.0.x).

I created a pull request (#61) with a failing test case.

BTW: It only fails on Ubuntu and passes on Mac.

**Comment by hypfvieh** [comment]
Should be fixed in Commit https://github.com/hypfvieh/dbus-java/commit/2a387f59a60f486e154f4957450743c4bb0ddab7
