### ISSUE TITLE
dbus & bluez - сharacteristic notification

### ISSUE THREAD

**Issue by vorobyev-aleksandr** [hypfvieh/dbus-java#75]
Hello to all!

Please help with the following problem. Mobile application does not receive сharacteristic notification. So I have an application that successfully writes and reads characteristic. To a specific characteristic, I added the flag 'notify'

For notification, I do this:

```
Map<String, Variant<?>> dict = new HashMap<>();
dict.put("Value", new Variant<>("hello".getBytes()));
Properties.PropertiesChanged message = new Properties.PropertiesChanged("/service/ble/service0/char0", "org.bluez.GattCharacteristic1", dict, new ArrayList<>());
connection.sendMessage(message);
```

dbus-monitor:
```
signal time=1570341966.172522 sender=:1.526 -> destination=(null destination) serial=41 path=/service/ble/service0/char0; interface=org.freedesktop.DBus.Properties; member=PropertiesChanged
   string "org.bluez.GattCharacteristic1"
   array [
      dict entry(
         string "Value"
         variant             array of bytes "hello"
      )
   ]
   array [
   ]

```
But on a mobile device, notification does not occur

Please tell me what can I do wrong?
It confuses me a little that there is no device in the request to which the notification is sent. But I don’t understand how to set  it (/org/bluez/hci0/dev_14_9F_3C_2F_C0_18)

**Comment by hypfvieh** [comment]
PropertiesChanged is a signal and cannot be used like that.

Signals in DBus are callbacks and they are executed by DBus if there is anything to tell you.
So creating and sending a Signal will simply do nothing at all.

To work with signals, your application has to register a signal handler for the signal you want to receive (like PropertiesChanged). Your code will then be call by DBus automatically.

So the stuff you want to do is simple change a property using setProperty on the Proeprties interfaces. DBus will then send the changes to bluez and bluez will propagate this to all connected devices.

**Comment by vorobyev-aleksandr** [comment]
Thanks for your reply.

If I understand your idea correctly:
class GattCharacteristic1Impl implements GattCharacteristic1,  Properties { 
...
    @Override
    public void WriteValue(byte[] value, Map<String, Variant<?>> params) {
        ....
        // I try like this
        Set("org.bluez.GattCharacteristic1", "Value", new Variant<>("hello".getBytes()));
    }
....
}

Does not work

**Comment by hypfvieh** [comment]
You are completely off the track...
If you want to write something to a characteristic, you first have to look it up on the bus.

Usually you will use bluez to look for bluetooth devices nearby by using the bluetooth adapter of your device (represented by a class implementing Adapter1 interface).
When you have found devices, you have  a Device1 interface instance of each device found.
On the found device you can than look for services (represented by GattService1). 

The GattService will than given you access to the characteristics (GattCharacteristic1) of the selected service.
Write your changes to that GattCharacteristic1 implementing class to change any value. 

Anyways, this is not a issue of dbus-java but of not understanding how DBus and bluez work.

For using bluez with java, take a look at [bluez-dbus](https://github.com/hypfvieh/bluez-dbus).
Please take a look at the provided classes there. If you still don't understand, try to read the bluez documentation.
