### ISSUE TITLE
Probably need "sun.misc" import declaration in pom.xml

### ISSUE THREAD

**Issue by s5uishida** [hypfvieh/dbus-java#78]
I haven't confirmed the operation, but I think that "sun.misc" import declaration probably needs to be added in `dbus-java-osgi/pom.xml`.
```
<Import-Package> org.slf4j,
==>  sun.misc,
　   org.eclipse.jdt.annotation;resolution:=optional 
</Import-Package>
```
When I checked bluez-dbus on OSGi, jnr-unixsocket depended on sun.misc, so the same situation will occur.

**Comment by s5uishida** [comment]
I confirmed that the "sun.misc" import declaration is necessary. Without this, the error was the same as for bluez-dbus-osgi.

**Comment by NatAmundsen** [comment]
I don't see `jnr-unixsocket` depending on sun.misc anymore in the latest release, and it doesn't provide that package, so now the use of `sun.misc` impedes compilation.
