### ISSUE TITLE
InterfaceCodeGenerator appears to generate Java code with errors

### ISSUE THREAD

**Issue by michaelNGV** [hypfvieh/dbus-java#82]
I hope this is just my experience or I was using the code improperly in some way.  I tried to generate the Java interface for [wireless](https://github.com/NetworkManager/NetworkManager/blob/master/introspection/org.freedesktop.NetworkManager.Device.Wireless.xml) but encountered the following in the generated code:

* the package declaration is `package org.freedesktop.networkmanager.device;` -- wrong case on networkmanager and device.
* The data members `_path` and `_interfaceName` are referenced but not declared.
* The data member `properties` is sometimes referenced as `_properties`.

**Comment by hypfvieh** [comment]
1) I added the `@DBusInterfaceName` annotation if the package name used on DBus is not compliant with java package naming scheme (e.g. contains upper case chars). Package names currently used were correct in terms of java, but wrong when using it on DBus.

2) Superclass arguments are no longer assigned in subclasses
3) Fixed the issue with wrong member name in constructors

**Comment by michaelNGV** [comment]
Quick workl  thank you!
