### ISSUE TITLE
Incorrect type for 'o' from InterfaceCodeGenerator

### ISSUE THREAD

**Issue by rm5248** [hypfvieh/dbus-java#83]
As seen in this [SO question](https://stackoverflow.com/questions/59061685/dbus-networkmanager-supply-as-dbusinterface-parameter-in-java)

Currently, `InterfaceCodeGenerator` maps the Dbus type of 'o' to be a `DBusInterface`.  This actually needs to be `DBusPath` in order to send and receive this type.

**Comment by hypfvieh** [comment]
Looks like the Marshalling class is already wrong (`InterfaceCodeGenerator` uses the Method `getJavaType` to find the Java-Class for a DBus type).

If changed the resulting type in Marshalling class [b6ca860](https://github.com/hypfvieh/dbus-java/commit/b6ca8605b5d8086b92bfe20c2481ca881ea23f20). I still have to check if this causes trouble elsewhere...
