### ISSUE TITLE
InterfaceCodeGenerator implementation example

### ISSUE THREAD

**Issue by yyvus** [hypfvieh/dbus-java#86]
Hi,

I find no where an example of the usage of the new way to create DBus Objects using the `InterfaceCodeGenerator` class. Could you guide me in finding a way to for example question the NetworkManager dbus object?

**Comment by hypfvieh** [comment]
The InterfaceCodeGenerator will only create the required java interface files, it will not create the objects.
It does exactly the same the old interface generator has done. 
The parameter are also the same as the old generator has required. 
For usage see help text using --help as parameter.

**Comment by yyvus** [comment]
Thanks for the comment. It helped a lot. I did manage to generate the interfaces using the `InterfaceCodeGenerator`, but it showed some errors. I create a new issue for clarity.
