### ISSUE TITLE
NetworkManager: Sender is not authorized to send message

### ISSUE THREAD

**Issue by yyvus** [hypfvieh/dbus-java#90]
This is certainly more a NetworkManager issue, but I am pretty sure this might be interesting to the different dbus implementation people might need to do.

A different behaviour occurs between the `nmcli` implementation and the dbus-java intent I am doing:
```
        NetworkManagerInterface networkManagerInterface = null;
        try{
            networkManagerInterface = getInstance().getRemoteObject( NetworkManagerInterface._NM_IFACE, NetworkManagerInterface._NM_PATH, NetworkManagerInterface.class );
            var result = networkManagerInterface.ActivateConnection( new DBusPath( accessPointProperties.getObjectPath() ), new DBusPath( "/" ), accessPointProperties.getDbusInterface() );
            LOGGER.info( "Attempting connection to " + accessPointProperties.SSID() + ";  result=" + (result == null ? "(nothing)" : result.getPath()) );

            return result != null;
        }catch(DBusException e){
            LOGGER.error( "Did not get properties:" + e.getMessage() );
            return false;
        }catch(DBusExecutionException e){
            LOGGER.error( "Could not activate connection:" + e.getMessage() );
            return false;
        }
```
The latter returns a 
```
Feb 03, 2020 14:34:00 ERROR PACKAGE.dbus.Wifi:492 - Could not activate connection:Sender is not authorized to send message
```
and the equivalent command line call `nmcli connection up SSID` return success without any credentials need.

See [SO](https://stackoverflow.com/questions/60040892/dbus-javanetworkmanager-sender-is-not-authorized-to-send-message)

How can I get the authorization to operate the code from within dbus-java?

**Comment by hypfvieh** [comment]
Sorry, this is really not an issue with dbus-java. 

I suggest you start reading the [networkmanager dbus documentation ](https://developer.gnome.org/NetworkManager/stable/spec.html) or read the sources. 

NetworkManager uses polkit to ensure only allowed programs/users can change network settings, so you may need to take a look at that (I guess tools like nmcli or nm-applet have some special polkit rules).

**Comment by yyvus** [comment]
Thanks. There is nothing about this in the doc. I will try to dig further. Thanks again.
