### ISSUE TITLE
EmbeddedDBusServer not working anymore

### ISSUE THREAD

**Issue by lbeuster** [hypfvieh/dbus-java#93]
Since 3.? the communication protocol in server mode seems to be broken. I copied 2 lines of code of the old 2.7 code of the Transport class and now it works for me. The server side never went from INITAL_STATE to WAIT_AUTH.

https://github.com/hypfvieh/dbus-java/pull/92

**Comment by hypfvieh** [comment]
Thanks. I merged your pull requests.

**Comment by lbeuster** [comment]
Thanks, any plans for a release?

**Comment by hypfvieh** [comment]
No release plans yet.
I'm thinking of a release if we fixed #81, but this will require some more time.

**Comment by lbeuster** [comment]
SNAPSHOT version works
