### ISSUE TITLE
ModemManager: Argument name "new" causes code-gen problems

### ISSUE THREAD

**Issue by andrm** [hypfvieh/dbus-java#95]
First of all, thank you for your work!

I'm trying to generate classes for ModemManager and stumbled on this:
org.freedesktop.ModemManager1.Modem.xml:
`  <signal name="StateChanged">
      <arg name="old"    type="i" />
      <arg name="new"    type="i" />
      <arg name="reason" type="u" />
    </signal>
`
Compiling the generated code leads to:
`build/dbusgenerated/org/freedesktop/modemmanager1/Modem.java:34: error: <identifier> expected
        private final int new;
                         ^
build/dbusgenerated/org/freedesktop/modemmanager1/Modem.java:52: error: <identifier> expected
            return new;
                      ^
`
Maybe they need to be "escaped" or otherwise subsituted.

**Comment by hypfvieh** [comment]
The only way to get this to work is to replace the variable names which conflicts with java language syntax. 

I pushed a fix for this issue which includes a set of reserved words which should be replaced. It may lack some words, but I hope it covers most.

Code is not tested yet, so please to a look and report back.

**Comment by rm5248** [comment]
FYI keyword list is here: https://docs.oracle.com/javase/tutorial/java/nutsandbolts/_keywords.html

**Comment by hypfvieh** [comment]
thanks, I updated the reserved word list
